version: "3"

volumes:
  symfony_2_db:

networks:
  symfony-2:

services:
  nginx:
    build: docker/nginx
    cap_drop: [all]
    cap_add: [chown, setgid, setuid, dac_override, net_bind_service]
    volumes:
      - ./:/var/www/symfony-2:cached
    ports:
      - 8001:80
    networks:
      - symfony-2
  php:
    build: docker/php
    cap_drop: [all]
    cap_add: [chown, setgid, setuid, dac_override]
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/symfony-2
    volumes:
      - ./:/var/www/symfony-2:cached
    networks:
      - symfony-2
  mysql:
    image: mysql:5.7
    cap_drop: [all]
    cap_add: [chown, setgid, setuid, dac_override]
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - symfony_2_db:/var/lib/mysql:cached
    ports:
      - 3311:3306
    networks:
      - symfony-2
